-- IMPORTANT: Please enable the 'vector' extension manually in Supabase:
-- Go to your Supabase Dashboard -> Database -> Extensions -> Search for "vector" and enable it.
-- (Running 'create extension' here sometimes causes read-only transaction errors)

-- Create the tweets table
create table if not exists public.tweets (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    tweet_text text not null,
    category text,
    embedding vector(768) -- Gemini embeddings are usually 768 dimensions
);

-- Create a function to search for similar tweets
-- This is used to check for >80% similarity
create or replace function match_tweets(
    query_embedding vector(768),
    match_threshold float,
    match_count int
)
returns table (
    id bigint,
    tweet_text text,
    similarity float
)
language sql stable
as $$
    select
        tweets.id,
        tweets.tweet_text,
        1 - (tweets.embedding <=> query_embedding) as similarity
    from tweets
    where 1 - (tweets.embedding <=> query_embedding) > match_threshold
    order by tweets.embedding <=> query_embedding
    limit match_count;
$$;
